name: CI/CD Workflow

on:
  pull_request:
    branches:
      - uat
      - main
      
  pull_request_review:
    types:
      - approved

env:
  DEV_CONNECTION_STRING: "string_de_dev"
  UAT_CONNECTION_STRING: "string_de_uat"
  PROD_CONNECTION_STRING: "string_de_prod"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Deploy to environment
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' && ${{ github.head_ref }} == 'dev' && ${{ github.base_ref }} == 'uat' ]]; then
            # Pull request from dev to uat, use DEV_CONNECTION_STRING
            echo "COND 1"
            echo "Deploying to dev environment with connection string $DEV_CONNECTION_STRING"
            python hello_world.py --connection-string $DEV_CONNECTION_STRING
          elif [[ ${{ github.head_ref }} == 'uat' && ${{ github.base_ref }} == 'main' && github.event.review.state == 'approved' ]]; then
            # Pull request from dev to uat closed (approved), use PROD_CONNECTION_STRING
            echo "COND 2"
            echo "Deploying to prod environment with connection string $PROD_CONNECTION_STRING"
            python hello_world.py --connection-string $PROD_CONNECTION_STRING
          elif [[ ${{ github.head_ref }} == 'uat' && ${{ github.base_ref }} == 'main' ]]; then
            # Pull request from uat to main, use UAT_CONNECTION_STRING
            echo "COND 3"
            echo "Deploying to UAT environment with connection string $UAT_CONNECTION_STRING"
            python hello_world.py --connection-string $UAT_CONNECTION_STRING
          fi
