name: Continuous Setup

on:
  workflow_dispatch:

jobs:
  setup_global:
    strategy:
      matrix:
        tools_list: [dbt, snowflake, sharepoint]
        
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Run setup for specified tool
        run: |
          tool_name=$(basename "${{ matrix.tools_list }}")
          echo "Running setup for $tool_name"
          cd "$tool_name"
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          fi
          if [ -f "setup.py" ]; then
            python setup.py
          fi
          cd ..
