name: Continuous Setup

on:
  push:
    branches:
      - master

jobs:
  job_setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          
      - name: Find tool folders
        id: find_folders
        run: |
          echo "::set-output name=folders::$(find . -type d -not -path './.git/*' -not -name 'template')"

      - name: Loop tool folders and run setup
        id: setup
        run: |
          find . -type d -not -path './.git/*' -not -name 'template' -exec bash -c '
            for folder do
              echo "folder -> ${folder}<-"
              tool_name=$(basename "$folder")
              echo "Running setup for ${tool_name}"
              cd "$folder"
              pip install -r requirements.txt
              python setup.py
              cd ..
              echo "setup_${tool_name}=true" >> $GITHUB_ENV
            done' bash {} +

  job_tests:
    runs-on: ubuntu-latest
    needs: job_setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      - name: Find tool folders
        id: find_folders
        run: |
          echo "::set-output name=folders::$(find . -type d -not -path './.git/*' -not -name 'template')"
          
      - name: Loop tool folders and run tests
        id: tests
        run: |
          find . -type d -not -path './.git/*' -not -name 'template' -exec bash -c '
            for folder do
              echo "folder -> ${folder}<-"
              tool_name=$(basename "$folder")
              echo "Running tests for ${tool_name}"
              cd "$folder"
              pip install -r requirements.txt
              python tests.py
              cd ..
            done' bash {} +
