name: Continuous Setup Global

on:
  workflow_dispatch:

jobs:
  setup_global:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Continuous Setup Base for each tool
        uses: actions/github-script@v4
        with:
          script: |
            const { Octokit } = require("@octokit/core");
            const octokit = new Octokit();

            const tools = ${{ toJSON(matrix.tools_list) }};
            for (const tool of tools) {
              console.log(`Starting Continuous Setup Base for ${tool}`);
              const createWorkflowRun = await octokit.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'continuous_setup_base.yml',
                ref: context.ref,
                inputs: {
                  setup_tool: tool
                }
              });
              console.log(`Workflow run created for ${tool}`);
            }
