name: Continuous Setup Global

on:
  workflow_dispatch:

jobs:
  setup_global:
    strategy:
      matrix:
        tools_list: [dbt, snowflake, sharepoint]
        
    uses: ./.github/workflows/continuous_setup_base.yml
    with:
      setup_tool: ${{ matrix.tools_list }}
