name: Continuous Setup Master

on:
  workflow_dispatch:

jobs:
  setup_master:
  
    strategy:
      matrix:
        setup_tools: [dbt, snowflake, sharepoint]
        
    uses: ./.github/workflows/continuous_setup_base.yml
    with:
      setup_tool: ${{ matrix.setup_tools }}

