name: Continuous Setup

on:
  push:
    branches:
      - main

jobs:
  setup_and_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find tool folders
        id: find_folders
        run: |
          echo "::set-output name=folders::$(find . -type d -not -path './.git/*' -not -name 'template')"

      - name: Setup and test
        run: |
          for folder in ${{ steps.find_folders.outputs.folders }}; do
            tool_name=$(basename "$folder")

            if [ "$tool_name" != "template" ]; then
              setup_job_name="setup_${tool_name}"
              tests_job_name="tests_${tool_name}"
              echo "Running setup for ${tool_name}"
              echo "##[group]$${setup_job_name}"
              echo "::set-output name=setup_job_name::$${setup_job_name}"
              python "$folder/setup.py"
              echo "::endgroup::"

              echo "Running tests for ${tool_name}"
              echo "##[group]$${tests_job_name}"
              echo "::set-output name=tests_job_name::$${tests_job_name}"
              python "$folder/tests.py"
              echo "::endgroup::"
            fi
          done

  ${{ needs.setup_and_tests.outputs.setup_job_name }}:
    runs-on: ubuntu-latest
    needs: setup_and_tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run setup
        run: echo "Running ${{ needs.setup_and_tests.outputs.setup_job_name }}"

  ${{ needs.setup_and_tests.outputs.tests_job_name }}:
    runs-on: ubuntu-latest
    needs: ${{ needs.setup_and_tests.outputs.setup_job_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: echo "Running ${{ needs.setup_and_tests.outputs.tests_job_name }}"
